export const programPaths = ['/sat-preparation-sharjah', '/language-trainings', '/academic-excellence', '/courses'];
export const contact = { phone: '+971527569908', mobile: '+971527569908', email: 'info@nitaqacademy.com' };
export const homeCopy = {
  en: {
    eyebrow: 'PREMIUM EDUCATION IN AL MAJAZ 3, SHARJAH', title: ['SAT Preparation.', 'Subject Tuition.', 'Language Training.'],
    intro: 'Prepare for the Digital SAT, strengthen your subject knowledge and develop your language skills with personalized academic support at Nitaq Academy.',
    explore: 'Explore Programs', admissions: 'Speak with Admissions', call: 'Call Admissions', book: 'Book a Diagnostic', view: 'View Programs',
    trust: ['Diagnostic-led guidance', 'Experienced tutors', 'Small-group learning'],
    highlights: [['Digital SAT', 'Focused preparation'], ['Subjects', 'Academic support'], ['Al Majaz 3', 'Sharjah, UAE']],
    journey: 'FROM POTENTIAL TO PROGRESS', scroll: 'Scroll to explore', skip: 'Skip to programs', start: 'Your next chapter starts here.',
    stages: [
      ['The foundation', 'Build the foundation for better results.', 'Every meaningful step forward starts with understanding where you are.'],
      ['Diagnostic Assessment', 'Clarity comes first.', 'Understand your current level before deciding what comes next.'],
      ['Personalized Learning Plan', 'A learning plan built around you.', 'Your goals. Your starting point. A clear, considered path forward.'],
      ['Focused Learning', 'Learn with focus.', 'Make room for deeper understanding with experienced tutors and personalized support.'],
      ['Guided Practice', 'Practice with purpose.', 'Turn understanding into confidence, one thoughtful question at a time.'],
      ['Progress Tracking', 'Progress you can see.', 'Use regular feedback to see what is improving and what to focus on next.'],
      ['Your Next Chapter', 'Ready for your next step?', 'Start with Nitaq Academy and build a clearer path toward your academic goals.'],
    ],
    diagnostic: 'Diagnostic', strengths: 'Strengths identified', focus: 'Focus areas identified', pathway: 'YOUR LEARNING PATH', subjects: ['SAT', 'English', 'Maths', 'Science'],
    tutor: 'Expert Tutors', tutorSub: 'Guided learning · Personalized support', practice: 'FOCUSED PRACTICE', question: 'One question. A clearer understanding.', completion: 'Practice, reflect, improve', readiness: 'SAT readiness', example: 'Example learning progression · Not actual results', success: 'A clearer path forward',
    programsEyebrow: 'FIND YOUR DIRECTION', programsTitle: 'Programs designed\naround your goals.', programsIntro: 'An ambitious next step. A stronger foundation. Whatever your goal, start with the right support.',
    programs: [
      ['SAT Preparation', 'Build a confident approach to the Digital SAT with strategy, guided practice and clear feedback.', 'Digital SAT · Strategy · Practice', 'Student preparing for a test on a laptop'],
      ['Language Training', 'Find your voice for study, work and everyday life through practical language learning.', 'English · Arabic · Communication', 'Adult learners practising conversation together'],
      ['Subject Tuition', 'Strengthen understanding and work through challenging concepts with focused academic support.', 'Maths · Science · Academic support', 'Student working through a problem with a tutor'],
      ['Other Courses', 'Explore professional, business and technology courses for the next stage of your journey.', 'Professional · Business · Technology', 'Books and learning materials on a study desk'],
    ],
    discover: 'Discover program',
    trustedTitle: 'TRUSTED BY LEADING ORGANIZATIONS',
    trustedSubtitle: "We deliver globally recognised professional training programs, built in partnership with the world's leading international organisations and certification bodies.",
    whyEyebrow: 'THE NITAQ APPROACH', whyTitle: 'Thoughtful support.\nMeaningful progress.', whyIntro: 'Good learning is personal. We bring structure, attention and purpose to every step of the journey.',
    benefits: [['Personalized Guidance', 'Start with your level, your priorities and the goals that matter to you.'], ['Focused Learning', 'A calm space to ask questions, explore ideas and build understanding.'], ['Experienced Tutors', 'Learn with educators who make challenging concepts feel approachable.'], ['Progress Tracking', 'Regular feedback helps you recognise growth and plan the next step.']],
    processEyebrow: 'A CLEAR WAY FORWARD', processTitle: 'Small steps. Lasting progress.', process: [['Assess', 'Understand your starting point.'], ['Plan', 'Build your learning pathway.'], ['Learn', 'Develop deeper understanding.'], ['Practice', 'Put your knowledge to work.'], ['Improve', 'Reflect, refine and move forward.']],
    locationEyebrow: 'ROOTED IN SHARJAH', locationTitle: 'Your ambitions.\nOur neighbourhood.', locationBody: 'A clearer academic future starts close to home. Visit Nitaq Academy in Al Majaz 3 and meet the team behind your next step.', address: 'Abu Khamseen Tower - Office : F103, Floor F1 - Al Majaz 3 - Al Majaz - Sharjah - United Arab Emirates', visit: 'Plan your visit', concept: 'Nitaq Academy micro-batch training classroom, Abu Khamseen Tower, Al Majaz 3, Sharjah.',
    ctaEyebrow: 'LET’S BEGIN', ctaTitle: 'Take the first step toward\nbetter academic progress.', ctaBody: 'Bring your questions, your goals and your potential. We’ll help you find your direction.',
    footerLine: 'A clearer path from potential to progress.', academy: 'Academy', contact: 'Get in touch', about: 'About Nitaq', resources: 'Learning resources', privacy: 'Privacy policy', terms: 'Terms & conditions', rights: 'All rights reserved.', menu: 'Open navigation', close: 'Close navigation', studentAlt: 'Focused university-age student studying at a modern desk with an open book, notebook and laptop',
  },
  ar: {
    eyebrow: 'تعليم متميز في المجاز 3، الشارقة', title: ['التحضير لاختبار SAT.', 'الدروس الأكاديمية.', 'تدريب اللغات.'],
    intro: 'استعد لاختبار SAT الرقمي، وعزّز معرفتك بالمواد الدراسية، وطوّر مهاراتك اللغوية مع دعم أكاديمي مخصص في أكاديمية نطاق.',
    explore: 'استكشف البرامج', admissions: 'تحدث مع القبول', call: 'اتصل بالقبول', book: 'احجز تقييماً', view: 'عرض البرامج', trust: ['إرشاد يبدأ بالتقييم', 'مدرسون ذوو خبرة', 'مجموعات صغيرة'], highlights: [['SAT الرقمي', 'تحضير مركّز'], ['المواد الدراسية', 'دعم أكاديمي'], ['المجاز 3', 'الشارقة، الإمارات']],
    journey: 'من الإمكانات إلى التقدّم', scroll: 'مرّر للاستكشاف', skip: 'انتقل إلى البرامج', start: 'فصلك القادم يبدأ هنا.',
    stages: [
      ['الأساس', 'ابنِ أساساً لنتائج أفضل.', 'تبدأ كل خطوة مهمة بفهم مستواك الحالي.'], ['التقييم التشخيصي', 'الوضوح أولاً.', 'افهم مستواك الحالي قبل تحديد الخطوة التالية.'], ['خطة تعلّم مخصصة', 'خطة تعلّم مصممة لك.', 'أهدافك ومستواك ومسار واضح يناسبك.'], ['التعلّم المركّز', 'تعلّم بتركيز.', 'افهم بعمق مع مدرسين ذوي خبرة ودعم فردي.'], ['التدريب الموجّه', 'تدرّب بهدف.', 'حوّل الفهم إلى ثقة، سؤالاً بعد سؤال.'], ['متابعة التقدّم', 'تقدّم يمكنك رؤيته.', 'تابع تحسّنك وحدّد أولوياتك من خلال الملاحظات المنتظمة.'], ['خطوتك القادمة', 'هل أنت مستعد لخطوتك التالية؟', 'ابدأ مع أكاديمية نطاق وابنِ مساراً أوضح نحو أهدافك الأكاديمية.'],
    ],
    diagnostic: 'التقييم', strengths: 'تحديد نقاط القوة', focus: 'تحديد مجالات التحسين', pathway: 'مسار تعلّمك', subjects: ['SAT', 'الإنجليزية', 'الرياضيات', 'العلوم'], tutor: 'مدرسون خبراء', tutorSub: 'تعلّم موجّه · دعم مخصص', practice: 'تدريب مركّز', question: 'سؤال واحد. فهم أوضح.', completion: 'تدرّب، تأمل، تحسّن', readiness: 'الاستعداد لاختبار SAT', example: 'مثال توضيحي للتقدّم · ليس نتائج فعلية', success: 'مسار أوضح إلى الأمام',
    programsEyebrow: 'اكتشف اتجاهك', programsTitle: 'برامج مصممة\nحول أهدافك.', programsIntro: 'خطوة طموحة وأساس أقوى. مهما كان هدفك، ابدأ بالدعم المناسب.',
    programs: [
      ['التحضير لاختبار SAT', 'استعد بثقة لاختبار SAT الرقمي مع استراتيجيات وتدريب موجّه وملاحظات واضحة.', 'SAT الرقمي · استراتيجيات · بالإنجليزية', 'طالبة تستعد للاختبار باستخدام حاسوب'],
      ['تدريب اللغات', 'طوّر تواصلك للدراسة والعمل والحياة اليومية من خلال تعلّم عملي.', 'الإنجليزية · العربية · بالإنجليزية', 'متعلّمات يتدربن على المحادثة'],
      ['الدروس الأكاديمية', 'عزّز فهمك للمفاهيم الصعبة مع دعم أكاديمي مركّز لطلاب المدارس والجامعات.', 'الرياضيات · العلوم · بالإنجليزية', 'طالب يحل مسألة بمساعدة مدرّس'],
      ['دورات أخرى', 'اكتشف الدورات المهنية والتجارية والتقنية لمرحلتك القادمة.', 'المهارات المهنية · الأعمال · بالإنجليزية', 'كتب وأدوات تعلّم على مكتب']
    ],
    discover: 'عرض تفاصيل البرنامج (بالإنجليزية)',
    trustedTitle: 'موثوق من قبل المنظمات الرائدة',
    trustedSubtitle: 'نقدم برامج تدريبية مهنية معترف بها عالمياً، بالشراكة مع كبرى المنظمات الدولية وهيئات الاعتماد العالمية.',
    whyEyebrow: 'نهج نطاق', whyTitle: 'دعم مدروس.\nتقدّم ملموس.', whyIntro: 'التعلّم الجيد تجربة شخصية. نقدّم الاهتمام والتنظيم والهدف في كل خطوة.',
    benefits: [['إرشاد مخصص', 'ابدأ بمستواك وأولوياتك والأهداف التي تهمّك.'], ['تعلّم مركّز', 'مساحة هادئة للأسئلة واستكشاف الأفكار وبناء الفهم.'], ['مدرسون ذوو خبرة', 'تعلّم مع مدرسين يبسّطون المفاهيم الصعبة.'], ['متابعة التقدّم', 'ملاحظات منتظمة لفهم تحسّنك والتخطيط للخطوة التالية.']],
    processEyebrow: 'طريق واضح إلى الأمام', processTitle: 'خطوات صغيرة. تقدّم مستمر.', process: [['قيّم', 'افهم نقطة انطلاقك.'], ['خطط', 'ابنِ مسار تعلّمك.'], ['تعلّم', 'طوّر فهماً أعمق.'], ['تدرّب', 'طبّق ما تعلّمته.'], ['تحسّن', 'راجع وطوّر وتقدّم.']],
    locationEyebrow: 'في قلب الشارقة', locationTitle: 'طموحاتك.\nفي مجتمعنا.', locationBody: 'مستقبل أكاديمي أوضح يبدأ بالقرب منك. زر أكاديمية نطاق في المجاز 3 وتعرّف على فريقنا.', address: 'برج أبو خمسين - مكتب F103، الطابق F1 - المجاز 3 - المجاز - الشارقة - الإمارات العربية المتحدة', visit: 'خطط لزيارتك', concept: 'فصل دراسي للمجموعات الصغيرة في أكاديمية نطاق، برج أبو خمسين، المجاز 3، الشارقة.',
    ctaEyebrow: 'لنبدأ', ctaTitle: 'اتخذ الخطوة الأولى\nنحو تقدّم أكاديمي أفضل.', ctaBody: 'أحضر أسئلتك وأهدافك وإمكاناتك. سنساعدك في تحديد اتجاهك.', footerLine: 'مسار أوضح من الإمكانات إلى التقدّم.', academy: 'الأكاديمية', contact: 'تواصل معنا', about: 'عن نطاق', resources: 'مصادر التعلّم', privacy: 'سياسة الخصوصية', terms: 'الشروط والأحكام', rights: 'جميع الحقوق محفوظة.', menu: 'افتح القائمة', close: 'أغلق القائمة', studentAlt: 'طالب جامعي يدرس على مكتب حديث مع كتاب مفتوح ودفتر وحاسوب',
  },
};
